"""
Turn seed/out/evaluations.json into a loadable Postgres script.

    python3 supabase/seed/make_seed_sql.py
    psql "$SUPABASE_DB_URL" -f supabase/seed/seed.sql

Why a SQL file rather than an API loader
----------------------------------------
The triggers in 0002_functions.sql deliberately refuse most of what seeding
needs to do: observations may only be inserted while an evaluation is in
'draft', and status transitions require a JWT role. That is correct
behaviour and should not be weakened for the convenience of a demo.

So the seed script disables those two triggers for the load and re-enables
them at the end, inside one transaction. This requires table-owner rights,
which the service-role / postgres connection has. Nothing about the
production rules is relaxed.

Every row is written with is_synthetic = true, which the
no_certificate_for_synthetic constraint uses to make certificate issue
impossible for this data.
"""

import json
import os
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "seed", "out", "evaluations.json")
OUT = os.path.join(HERE, "seed.sql")

LAB_CODES = {
    "RRSL-AMD": "01", "RRSL-BLR": "02", "RRSL-BBS": "03", "RRSL-FBD": "04",
    "RRSL-GHY": "05", "RRSL-JAI": "06", "RRSL-MUM": "07", "RRSL-VNS": "08",
}


def q(v):
    """Quote a value for SQL."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    evals = json.load(open(SRC))

    # --- dedup manufacturers and models --------------------------------
    manufacturers = OrderedDict()
    models = OrderedDict()
    for ev in evals:
        i = ev["instrument"]
        manufacturers.setdefault(i["manufacturer"], None)
        key = (i["manufacturer"], i["model"])
        if key not in models:
            models[key] = i

    out = []
    w = out.append

    w("-- =====================================================================")
    w("-- seed.sql — synthetic demo dataset for PS 26035")
    w("-- Generated by supabase/seed/make_seed_sql.py. Do not edit by hand.")
    w(f"-- {len(evals)} evaluations, "
      f"{sum(len(e['observations']) for e in evals)} observations, "
      f"{len(models)} models, {len(manufacturers)} manufacturers.")
    w("--")
    w("-- EVERY ROW IS SYNTHETIC. The no_certificate_for_synthetic constraint")
    w("-- makes it impossible to issue a certificate against any of it.")
    w("-- =====================================================================")
    w("")
    w("begin;")
    w("")
    w("-- The guard triggers exist to stop exactly what a bulk load does:")
    w("-- writing observations into non-draft evaluations and setting status")
    w("-- without a JWT role. Disable them for the load only.")
    w("alter table evaluation  disable trigger evaluation_guard;")
    w("alter table observation disable trigger observation_guard;")
    w("alter table evaluation  disable trigger audit_evaluation;")
    w("alter table observation disable trigger audit_observation;")
    w("")

    # --- manufacturers --------------------------------------------------
    w("-- manufacturers ------------------------------------------------------")
    w("-- Bare 'on conflict do nothing' throughout: it binds to whatever")
    w("-- unique constraint or index exists rather than naming columns, so it")
    w("-- survives manufacturer's expression index on")
    w("-- (lower(name), coalesce(lower(city), '')), which a targeted clause")
    w("-- cannot match.")
    w("insert into manufacturer (name, country) values")
    w(",\n".join(f"  ({q(n)}, 'India')" for n in manufacturers))
    w("on conflict do nothing;")
    w("")

    # --- instrument models ----------------------------------------------
    w("-- instrument models --------------------------------------------------")
    for (mfr, model), i in models.items():
        w(f"""insert into instrument_model (
  manufacturer_id, model, instrument_type, accuracy_class,
  max_capacity_g, e_g, d_g, min_capacity_g,
  indication_type, is_electronic, has_tare_device,
  temp_low_c, temp_high_c, software_version, software_checksum)
select m.id, {q(model)}, {q(i['type'])}, {q(i['accuracy_class'])}::accuracy_class,
       {q(i['max_capacity_g'])}, {q(i['e_g'])}, {q(i['d_g'])}, {q(i['min_capacity_g'])},
       {q(i['indication_type'])}::indication_type, {q(i['is_electronic'])},
       {q(i['has_tare_device'])},
       {q(i['temp_range_c'][0])}, {q(i['temp_range_c'][1])},
       {q(i['software_version'])}, {q(i['software_checksum'])}
from manufacturer m where m.name = {q(mfr)}
on conflict do nothing;""")
    w("")

    # --- evaluations ----------------------------------------------------
    w("-- evaluations ---------------------------------------------------------")
    for ev in evals:
        i = ev["instrument"]
        w(f"""insert into evaluation (
  ref, lab_id, model_id, serial_no, standard_id, jurisdiction,
  status, verdict, zero_error_g, approval_mark,
  weight_set_id, load_cell, is_synthetic, generator_version, created_at)
select {q(ev['ref'])},
       l.id, im.id, {q(i['serial'])},
       {q(ev['standard_id'])}, 'IN',
       {q(ev['status'])}::evaluation_status,
       {q(ev['verdict'])}::verdict,
       {q(ev['zero_error_g'])},
       {q(ev['approval_mark'])},
       {q(i['weight_set'])}, {q(i['load_cell'])},
       true, {q(ev['generator_version'])}, {q(ev['created_at'])}::timestamptz
from lab l
join manufacturer m on m.name = {q(i['manufacturer'])}
join instrument_model im
  on im.manufacturer_id = m.id and im.model = {q(i['model'])}
where l.code = {q(ev['lab_code'])}
on conflict do nothing;""")
    w("")

    # --- observations ----------------------------------------------------
    w("-- observations --------------------------------------------------------")
    w("-- No temporary table: the Supabase SQL Editor commits statement by")
    w("-- statement, so a temp table created with ON COMMIT DROP is destroyed")
    w("-- the moment it is created and the next statement cannot see it.")
    w("-- A VALUES list joined straight to evaluation needs no staging at all,")
    w("-- and works the same in the editor and in psql.")
    w("")

    rows = []
    for ev in evals:
        for n_, o in enumerate(ev["observations"], 1):
            sev = {"disturbance": o["disturbance"]} if o.get("disturbance") else None
            rows.append(
                f"({q(ev['ref'])},{q(o.get('test_code'))},{q(o.get('variant'))},{n_},"
                f"{q(o.get('load_g'))},{q(o.get('indication_g'))},{q(o.get('delta_load_g'))},"
                f"{q(o.get('direction'))},{q(o.get('position'))},"
                f"{q(o.get('elapsed_minutes'))},{q(o.get('weighing_no'))},"
                f"{q(o.get('indication_without_g'))},{q(o.get('indication_with_g'))},"
                f"{q(o.get('significant_fault_detected'))},{q(sev)})"
            )

    COLS = ("evaluation_id, test_code, variant, sequence_no,\n"
            "  load_g, indication_g, delta_load_g, direction, position,\n"
            "  elapsed_minutes, weighing_no,\n"
            "  indication_without_g, indication_with_g,\n"
            "  significant_fault_detected, severity")

    # The first row of a VALUES list fixes the column types, and many of
    # these columns are NULL in row 1. Cast that row explicitly so the
    # planner does not infer text and then fail on a numeric further down.
    CAST = ("v.ref, v.test_code, v.variant, v.sequence_no::int,\n"
            "       v.load_g::numeric, v.indication_g::numeric, v.delta_load_g::numeric,\n"
            "       v.direction, v.position, v.elapsed_minutes::int, v.weighing_no::int,\n"
            "       v.indication_without_g::numeric, v.indication_with_g::numeric,\n"
            "       v.significant_fault_detected::boolean, v.severity::jsonb")

    CHUNK = 400
    for k in range(0, len(rows), CHUNK):
        w(f"insert into observation (\n  {COLS})")
        w("select e.id,")
        w("       " + CAST.split("v.ref, ", 1)[1])
        w("from (values")
        w(",\n".join(rows[k:k + CHUNK]))
        w(") as v(ref, test_code, variant, sequence_no, load_g, indication_g,")
        w("       delta_load_g, direction, position, elapsed_minutes, weighing_no,")
        w("       indication_without_g, indication_with_g,")
        w("       significant_fault_detected, severity)")
        w("join evaluation e on e.ref = v.ref")
        w("on conflict do nothing;")
        w("")

    w("-- restore the guards --------------------------------------------------")
    w("alter table evaluation  enable trigger evaluation_guard;")
    w("alter table observation enable trigger observation_guard;")
    w("alter table evaluation  enable trigger audit_evaluation;")
    w("alter table observation enable trigger audit_observation;")
    w("")
    w("commit;")
    w("")
    w("-- verification ---------------------------------------------------------")
    w("""select 'evaluations' as what, count(*) from evaluation
union all select 'observations', count(*) from observation
union all select 'models',       count(*) from instrument_model
union all select 'manufacturers',count(*) from manufacturer;""")
    w("")
    w("select status, count(*) from evaluation group by status order by 2 desc;")
    w("select verdict, count(*) from evaluation group by verdict;")
    w("select * from v_dashboard_counts order by total desc;")
    w("")
    w("-- must return zero rows: no synthetic row may carry a certificate")
    w("""select ref, status, certificate_no, gazette_date from evaluation
where is_synthetic and (certificate_no is not null or gazette_date is not null);""")

    open(OUT, "w").write("\n".join(out) + "\n")

    size = os.path.getsize(OUT)
    print(f"wrote {OUT}")
    print(f"  {len(evals)} evaluations")
    print(f"  {len(rows)} observations")
    print(f"  {len(models)} instrument models")
    print(f"  {len(manufacturers)} manufacturers")
    print(f"  {size/1e6:.1f} MB")


if __name__ == "__main__":
    main()
